name: Deploy GitHub Page

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  Home-Page:
    
    runs-on: ubuntu-latest
    
    steps:
      
    - name: Git Checkout
      uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
      
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: production
        FOLDER: dist
        BUILD_SCRIPT: npm install && npm run build -- --prod
